Elcodi\Component\Product\Entity\Variant:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\VariantRepository
    table: variant
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        sku:
            column: sku
            type: string
            length: 255
            nullable: true
        stock:
            column: stock
            type: integer
            nullable: true
        price:
            column: price
            type: integer
            nullable: true
        reducedPrice:
            column: reduced_price
            type: integer
            nullable: true
        height:
            column: height
            type: integer
            nullable: false
        width:
            column: width
            type: integer
            nullable: false
        depth:
            column: depth
            type: integer
            nullable: false
        weight:
            column: weight
            type: integer
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
            nullable: true

    manyToOne:
        product:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\ProductInterface
            inversedBy: variants
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
        principalImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: principal_image_id
                referencedColumnName: id
                nullable: true
        priceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: price_currency_id
                referencedColumnName: id
                nullable: true
        reducedPriceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: reduced_price_currency_id
                referencedColumnName: id
                nullable: true

    manyToMany:
        options:
            targetEntity: Elcodi\Component\Attribute\Entity\Interfaces\ValueInterface
            joinTable:
                name: variant_options
                joinColumns:
                    variant_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    option_id:
                        referencedColumnName: id
        images:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinTable:
                name: variant_image
                joinColumns:
                    variant_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
